export const LANDING_ES = {
  heroTitle: 'DOMINA TU TIEMPO',
  heroSubtitle: 'ORGANIZA TU VIDA',
  heroDesc:
    'Gestiona tus tareas con priorizacion automatica, analisis de productividad y asistencia con inteligencia artificial',
  btnCreate: 'Crear cuenta',
  btnExplore: 'Explorar funcionalidades',
  queTitle: '¿Qué hace TaskMaster?',
  queDesc: 'TaskMaster está diseñado para que seas más eficiente cada día.',
  b1h: 'Priorización Inteligente',
  b1p: 'Ordena automáticamente tus tareas según fecha y urgencia.',
  b2h: 'Seguimiento de Productividad',
  b2p: 'Visualiza tu progreso con estadísticas claras.',
  b3h: 'Asistente IA',
  b3p: 'Divide tareas complejas y mejora tus hábitos.',
  boardH: 'Visualiza tus tareas en un tablero organizado',
  boardP:
    'Mantén el control total de tus actividades con un tablero por estado. Arrastra, prioriza y avanza sin perder el foco.',
  boardLi1: 'Organiza por columnas: Pendiente, En proceso, Hecho',
  boardLi2: 'Arrastra y suelta para cambiar el estado',
  boardLi3: 'Vista clara de todo tu progreso',
  mockBoard: 'Mi Tablero',
  colPending: 'PENDIENTE',
  colProgress: 'EN PROCESO',
  colDone: 'HECHO',
  mockT1: 'Revisar informe',
  mockT2: 'Llamar al cliente',
  mockT3: 'Diseño UI',
  mockT4: 'Reunión equipo',
  mockT5: 'Documentación',
  mockT6: 'Revisar correos',
  mockT7: 'Actualizar datos',
  pmTitle: 'Mis tareas',
  pmBadge: 'Hoy',
  pmTask1: 'Entrega informe Q1',
  pmTask2: 'Llamada proveedor',
  pmTask3: 'Revisar presupuesto',
  pmUrgent: 'Urgente',
  pmMid: 'Media',
  pmLow: 'Baja',
  pmD1: 'Mar 12 · 18:00',
  pmD2: 'Mar 14 · 10:30',
  pmD3: 'Mar 18',
  splitPriH: 'Fecha límite y prioridad alineadas',
  splitPriLead:
    'Cada tarea lleva urgencia y vencimiento visibles. Así el tablero y la lista dicen lo mismo: menos suposiciones al planificar el día.',
  splitPri1: 'Fecha y hora en un solo campo para anclar entregas reales.',
  splitPri2: 'Cuatro niveles de prioridad para ordenar sin pelear con el calendario mental.',
  splitPri3: 'Descripción opcional cuando el título no basta.',
  splitDashH: 'Un resumen antes de entrar al detalle',
  splitDashLead:
    'El panel te muestra totales, pendientes, completadas y tareas vencidas. Ideal para decidir si abres la lista o primero recortas carga.',
  splitDash1: 'Porcentaje de cumplimiento de un vistazo.',
  splitDash2: 'Detecta cuellos de botella antes de sumar tareas nuevas.',
  splitDash3: 'Complementa el tablero: mismo criterio, otra perspectiva.',
  statsTitle: 'Resumen',
  statTotal: 'Total',
  statDone: 'Completadas',
  statPending: 'Pendientes',
  statOverdue: 'Vencidas',
  statCompliance: 'Cumplimiento',
  iaEyebrow: 'Inteligencia artificial',
  iaH: '¿Un proyecto grande te abruma?',
  iaP:
    'El asistente IA propone pasos, divide bloques y sugiere prioridades para que el tablero no se llene de títulos imposibles de empezar.',
  iaGhost: 'Conocer el asistente',
  iaSolid: 'Crear cuenta',
} as const;

export const LANDING_EN: { [K in keyof typeof LANDING_ES]: string } = {
  heroTitle: 'MASTER YOUR TIME',
  heroSubtitle: 'ORGANIZE YOUR LIFE',
  heroDesc:
    'Manage tasks with automatic prioritization, productivity insights, and AI assistance',
  btnCreate: 'Create account',
  btnExplore: 'Explore features',
  queTitle: 'What does TaskMaster do?',
  queDesc: 'TaskMaster is designed to make you more efficient every day.',
  b1h: 'Smart prioritization',
  b1p: 'Automatically order tasks by date and urgency.',
  b2h: 'Productivity tracking',
  b2p: 'See your progress with clear statistics.',
  b3h: 'AI assistant',
  b3p: 'Break down complex tasks and improve your habits.',
  boardH: 'See your tasks on a tidy board',
  boardP:
    'Stay in control with a board by status. Drag, prioritize, and move forward without losing focus.',
  boardLi1: 'Columns: To do, In progress, Done',
  boardLi2: 'Drag and drop to change status',
  boardLi3: 'A clear view of all your progress',
  mockBoard: 'My board',
  colPending: 'TO DO',
  colProgress: 'IN PROGRESS',
  colDone: 'DONE',
  mockT1: 'Review report',
  mockT2: 'Call client',
  mockT3: 'UI design',
  mockT4: 'Team meeting',
  mockT5: 'Documentation',
  mockT6: 'Check email',
  mockT7: 'Update data',
  pmTitle: 'My tasks',
  pmBadge: 'Today',
  pmTask1: 'Q1 report delivery',
  pmTask2: 'Vendor call',
  pmTask3: 'Review budget',
  pmUrgent: 'Urgent',
  pmMid: 'Medium',
  pmLow: 'Low',
  pmD1: 'Mar 12 · 6:00 PM',
  pmD2: 'Mar 14 · 10:30 AM',
  pmD3: 'Mar 18',
  splitPriH: 'Due dates and priority aligned',
  splitPriLead:
    'Every task shows urgency and due date. Board and list tell the same story—fewer guesses when planning your day.',
  splitPri1: 'Date and time in one field for real deliveries.',
  splitPri2: 'Four priority levels without fighting your mental calendar.',
  splitPri3: 'Optional description when the title is not enough.',
  splitDashH: 'A summary before the details',
  splitDashLead:
    'The dashboard shows totals, pending, completed, and overdue—so you can open the list or trim load first.',
  splitDash1: 'Completion rate at a glance.',
  splitDash2: 'Spot bottlenecks before adding more tasks.',
  splitDash3: 'Complements the board: same rules, another angle.',
  statsTitle: 'Summary',
  statTotal: 'Total',
  statDone: 'Completed',
  statPending: 'Pending',
  statOverdue: 'Overdue',
  statCompliance: 'Completion',
  iaEyebrow: 'Artificial intelligence',
  iaH: 'Is a big project overwhelming?',
  iaP:
    'The AI assistant suggests steps, splits work, and recommends priorities so your board is not full of impossible starters.',
  iaGhost: 'Meet the assistant',
  iaSolid: 'Create account',
};
