import { LANDING_EN, LANDING_ES } from './ui-strings-landing';
import { FUNCIONALIDADES_EN, FUNCIONALIDADES_ES } from './ui-strings-funcionalidades';
import { PRODUCTIVIDAD_PAGE_EN, PRODUCTIVIDAD_PAGE_ES } from './ui-strings-productividad';
import { ASISTENTE_IA_PAGE_EN, ASISTENTE_IA_PAGE_ES } from './ui-strings-asistente-ia-page';
import { NOSOTROS_PAGE_EN, NOSOTROS_PAGE_ES } from './ui-strings-nosotros-page';

/** Amplía literales de cadena para que ES y EN compartan la misma forma tipada. */
type DeepStrings<T> = T extends string
  ? string
  : T extends readonly (infer U)[]
    ? U extends string
      ? readonly string[]
      : ReadonlyArray<DeepStrings<U>>
    : T extends object
      ? { [K in keyof T]: DeepStrings<T[K]> }
      : T;

/**
 * Textos de interfaz (ES/EN) alineados con AppSettingsService.settings().idioma
 */
export const UI_ES = {
  header: {
    menuToggle: 'Abrir o cerrar menú de navegación',
    home: 'Inicio',
    features: 'Funcionalidades',
    productivity: 'Productividad',
    aiAssistant: 'Asistente IA',
    about: 'Nosotros',
    searchSite: 'Buscar en el sitio',
    searchPlaceholder: 'Buscar...',
    searchTerm: 'Término de búsqueda',
    account: 'Mi cuenta',
    signIn: 'Iniciar sesión',
  },
  /** Misma forma que el objeto L() de configuración (Mi configuración) */
  config: {
    subtitle: 'Gestiona tu cuenta',
    newTask: '+ Nueva Tarea',
    apariencia: 'Apariencia',
    tema: 'Tema',
    claro: 'Claro',
    oscuro: 'Oscuro',
    sistema: 'Sistema',
    fontSize: 'Tamaño de fuente',
    general: 'General',
    idioma: 'Idioma',
    dateFormat: 'Formato de fecha',
    timeFormat: 'Formato de hora',
    timezone: 'Zona horaria',
    notificaciones: 'Notificaciones',
    n1: 'Recordatorios de vencimiento',
    n1h: '1 día y 3 horas antes',
    n2: 'Resumen diario',
    n2h: 'Tareas pendientes cada mañana',
    n3: 'Resumen semanal',
    n3h: 'Productividad cada lunes',
    n4: 'Sonidos',
    n4h: 'Al recibir notificaciones nuevas',
    n5: 'Notificaciones en el escritorio',
    n5h: 'Avisos del sistema para vencimientos',
    notifFooter: 'Ir al centro de notificaciones',
    productividad: 'Productividad',
    prodRange: 'Periodo por defecto en informes',
    insights: 'Mostrar insights rápidos',
    insightsHint: 'Consejos en la vista de productividad',
    prodFooter: 'Ver panel completo de productividad',
  },
  common: {
    accountSubtitle: 'Gestiona tu cuenta',
    newTask: '+ Nueva Tarea',
    loading: 'Cargando…',
  },
  tasks: {
    title: 'Mis Tareas',
    filterByDate: 'Filtrar por fecha',
    today: 'Hoy',
    thisWeek: 'Esta semana',
    all: 'Todas',
    newTask: '+ Nueva tarea',
    empty: 'No hay tareas en esta vista.',
    createOne: 'Crear una',
    edit: 'Editar',
    delete: 'Eliminar',
  },
  taskForm: {
    back: '← Volver',
    newTitle: 'Nueva tarea',
    editTitle: 'Editar tarea',
    needSession:
      'Para guardar tareas necesitas una sesión iniciada.',
    signIn: 'Iniciar sesión',
    titleLabel: 'Título',
    titlePlaceholder: 'Nombre de la tarea',
    titleError: 'El título es obligatorio',
    description: 'Descripción',
    descPlaceholder: 'Detalles opcionales',
    due: 'Fecha límite',
    dueError: 'Fecha obligatoria',
    priority: 'Prioridad',
    prioBaja: 'Baja',
    prioMedia: 'Media',
    prioAlta: 'Alta',
    prioUrgente: 'Urgente',
    saving: 'Guardando...',
    saveEdit: 'Guardar cambios',
    create: 'Crear tarea',
    cancel: 'Cancelar',
  },
  dashboard: {
    weekCol: 'SEMANA',
    weekdays: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'],
    prevMonth: 'Mes anterior',
    nextMonth: 'Mes siguiente',
    close: 'Cerrar',
    holidayPrefix: 'Festivo:',
    addEmoji: 'Añadir texto o emojis',
    quickEmojis: 'Emojis rápidos',
    insertEmoji: 'Insertar',
    notePlaceholder: 'Escribe aquí… (también puedes pegar emojis desde el teclado)',
    saveOnDate: 'Guardar en esta fecha',
    deleteNote: 'Eliminar nota',
    titleEditNotes: 'Editar notas',
    titleAddNotes: 'Añadir notas',
  },
  profile: {
    activitySummary: 'Resumen de actividad',
    completedTasks: 'Tareas completadas',
    streakDays: 'Días de racha',
    compliance: 'Cumplimiento',
    personalInfo: 'Información personal',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo',
    role: 'Rol',
    phFirst: 'Tu nombre',
    phLast: 'Tu apellido',
    phEmail: 'correo@ejemplo.com',
    save: 'Guardar cambios',
    hint: 'Usamos estos datos para personalizar tus recomendaciones.',
    roleStudent: 'Estudiante',
    rolePro: 'Profesional',
    roleOther: 'Otro',
  },
  notifications: {
    centerTitle: 'Centro de notificaciones',
    unreadBadge: 'No leídas',
    markAllRead: 'Marcar todas leídas',
    filterGroup: 'Filtrar notificaciones',
    filterAll: 'Todas',
    filterPending: 'Pendientes',
    filterRead: 'Leídas',
    markRead: 'Marcar leído',
    empty: 'No hay notificaciones en esta vista.',
    prefsTitle: 'Preferencias',
    p1: 'Recordatorios de vencimiento',
    p1h: '1 día y 3 horas antes',
    p2: 'Resumen diario',
    p2h: 'Tareas pendientes cada mañana',
    p3: 'Resumen semanal',
    p3h: 'Productividad cada lunes',
    p4: 'Sonidos',
    p4h: 'Al recibir notificaciones',
    p5: 'Notificaciones en el escritorio',
    p5h: 'Avisos del sistema para tareas próximas a vencer (requiere permiso)',
  },
  userProductividad: {
    period: 'Periodo',
    last7: 'Últimos 7 días',
    last30: 'Últimos 30 días',
    loading: 'Cargando...',
    overview: 'Visión general',
    completed: 'Completadas',
    compliance: 'Cumplimiento',
    streak: 'Días seguidos',
    insightsTitle: 'Insights rápidos',
    activityByDay: 'Actividad por día',
    chartBars: 'Gráfico de barras por día',
    priorities: 'Prioridades',
    noPending: 'No hay tareas pendientes en este periodo.',
    insights: [
      'Sueles completar más tareas los martes.',
      'Las tareas de alta prioridad se cumplen a tiempo el 80%.',
      'Usas más TaskMaster en la noche.',
    ],
  },
  buscar: {
    title: 'Resultados de búsqueda',
    matchesFor: 'Mostrando coincidencias para',
    explore: 'Explora las secciones del sitio. Escribe arriba para filtrar.',
    empty:
      'No hay resultados. Prueba con otras palabras (por ejemplo: tareas, IA, nosotros).',
  },
  auth: {
    loginEmail: 'Correo electrónico',
    loginEmailPh: 'Correo Electronico',
    loginEmailErr: 'Correo inválido',
    password: 'Contraseña',
    pwdErr: 'Mínimo 6 caracteres',
    forgot: '¿Olvidaste tu contraseña?',
    signingIn: 'Entrando...',
    signIn: 'Inicia sesión',
    noAccount: '¿No tienes una cuenta?',
    registerHere: 'Regístrate aquí',
    registerName: 'Nombre',
    registerNameErr: 'Mínimo 2 caracteres',
    confirmPassword: 'Confirmar contraseña',
    confirmMismatch: 'Las contraseñas no coinciden',
    creating: 'Creando cuenta...',
    createAccount: 'Crear cuenta',
    hasAccount: '¿Ya tienes cuenta?',
    signInHere: 'Inicia sesión aquí',
  },
  userAsistente: {
    conversations: 'Conversaciones',
    placeholder: 'Escribe un mensaje…',
    send: 'Enviar',
    hint: 'El asistente usa tus tareas para sugerir el siguiente paso.',
  },
  asistentePublic: {
    heroTitle: '¿Qué hace el asistente IA?',
    heroSubtitle:
      'Analiza tus tareas y te recomienda cómo organizar tu tiempo de forma inteligente.',
  },
  nosotros: {
    teamTitle: 'Equipo de Desarrollo',
    avatarAlt: 'Avatar ilustrado de',
    aboutTitle: 'Sobre el proyecto',
    aboutLead:
      'TaskMaster es un <strong>prototipo académico</strong> de gestor inteligente de tareas personales: une una interfaz web sencilla con ideas de productividad y un asistente basado en IA para ayudarte a decidir qué hacer primero. Está pensado como demostración de buenas prácticas de desarrollo, accesibilidad y trabajo en equipo.',
    ideasLabel: 'Ideas clave',
  },
  funcionalidadesPage: FUNCIONALIDADES_ES,
  productividadPage: PRODUCTIVIDAD_PAGE_ES,
  asistenteIaPage: ASISTENTE_IA_PAGE_ES,
  nosotrosPage: NOSOTROS_PAGE_ES,
  landing: LANDING_ES,
} as const;

export const UI_EN: DeepStrings<typeof UI_ES> = {
  header: {
    menuToggle: 'Open or close navigation menu',
    home: 'Home',
    features: 'Features',
    productivity: 'Productivity',
    aiAssistant: 'AI assistant',
    about: 'About us',
    searchSite: 'Search the site',
    searchPlaceholder: 'Search...',
    searchTerm: 'Search query',
    account: 'My account',
    signIn: 'Sign in',
  },
  config: {
    subtitle: 'Manage your account',
    newTask: '+ New task',
    apariencia: 'Appearance',
    tema: 'Theme',
    claro: 'Light',
    oscuro: 'Dark',
    sistema: 'System',
    fontSize: 'Font size',
    general: 'General',
    idioma: 'Language',
    dateFormat: 'Date format',
    timeFormat: 'Time format',
    timezone: 'Time zone',
    notificaciones: 'Notifications',
    n1: 'Due date reminders',
    n1h: '1 day and 3 hours before',
    n2: 'Daily summary',
    n2h: 'Pending tasks each morning',
    n3: 'Weekly summary',
    n3h: 'Productivity every Monday',
    n4: 'Sounds',
    n4h: 'When new notifications arrive',
    n5: 'Desktop notifications',
    n5h: 'System alerts for due dates',
    notifFooter: 'Go to notification center',
    productividad: 'Productivity',
    prodRange: 'Default period in reports',
    insights: 'Show quick insights',
    insightsHint: 'Tips on the productivity view',
    prodFooter: 'View full productivity dashboard',
  },
  common: {
    accountSubtitle: 'Manage your account',
    newTask: '+ New task',
    loading: 'Loading…',
  },
  tasks: {
    title: 'My tasks',
    filterByDate: 'Filter by date',
    today: 'Today',
    thisWeek: 'This week',
    all: 'All',
    newTask: '+ New task',
    empty: 'No tasks in this view.',
    createOne: 'Create one',
    edit: 'Edit',
    delete: 'Delete',
  },
  taskForm: {
    back: '← Back',
    newTitle: 'New task',
    editTitle: 'Edit task',
    needSession: 'You need to be signed in to save tasks.',
    signIn: 'Sign in',
    titleLabel: 'Title',
    titlePlaceholder: 'Task name',
    titleError: 'Title is required',
    description: 'Description',
    descPlaceholder: 'Optional details',
    due: 'Due date',
    dueError: 'Date is required',
    priority: 'Priority',
    prioBaja: 'Low',
    prioMedia: 'Medium',
    prioAlta: 'High',
    prioUrgente: 'Urgent',
    saving: 'Saving...',
    saveEdit: 'Save changes',
    create: 'Create task',
    cancel: 'Cancel',
  },
  dashboard: {
    weekCol: 'WEEK',
    weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    close: 'Close',
    holidayPrefix: 'Holiday:',
    addEmoji: 'Add text or emojis',
    quickEmojis: 'Quick emojis',
    insertEmoji: 'Insert',
    notePlaceholder: 'Write here… (you can paste emojis from the keyboard too)',
    saveOnDate: 'Save on this date',
    deleteNote: 'Delete note',
    titleEditNotes: 'Edit notes',
    titleAddNotes: 'Add notes',
  },
  profile: {
    activitySummary: 'Activity summary',
    completedTasks: 'Tasks completed',
    streakDays: 'Streak days',
    compliance: 'Completion',
    personalInfo: 'Personal information',
    firstName: 'First name',
    lastName: 'Last name',
    email: 'Email',
    role: 'Role',
    phFirst: 'Your first name',
    phLast: 'Your last name',
    phEmail: 'email@example.com',
    save: 'Save changes',
    hint: 'We use this data to personalize your recommendations.',
    roleStudent: 'Student',
    rolePro: 'Professional',
    roleOther: 'Other',
  },
  notifications: {
    centerTitle: 'Notification center',
    unreadBadge: 'Unread',
    markAllRead: 'Mark all as read',
    filterGroup: 'Filter notifications',
    filterAll: 'All',
    filterPending: 'Pending',
    filterRead: 'Read',
    markRead: 'Mark as read',
    empty: 'No notifications in this view.',
    prefsTitle: 'Preferences',
    p1: 'Due date reminders',
    p1h: '1 day and 3 hours before',
    p2: 'Daily summary',
    p2h: 'Pending tasks each morning',
    p3: 'Weekly summary',
    p3h: 'Productivity every Monday',
    p4: 'Sounds',
    p4h: 'When notifications arrive',
    p5: 'Desktop notifications',
    p5h: 'System alerts for upcoming due tasks (permission required)',
  },
  userProductividad: {
    period: 'Period',
    last7: 'Last 7 days',
    last30: 'Last 30 days',
    loading: 'Loading...',
    overview: 'Overview',
    completed: 'Completed',
    compliance: 'Completion',
    streak: 'Streak days',
    insightsTitle: 'Quick insights',
    activityByDay: 'Activity by day',
    chartBars: 'Bar chart by day',
    priorities: 'Priorities',
    noPending: 'No pending tasks in this period.',
    insights: [
      'You tend to complete more tasks on Tuesdays.',
      'High-priority tasks are on time about 80% of the time.',
      'You use TaskMaster more in the evening.',
    ],
  },
  buscar: {
    title: 'Search results',
    matchesFor: 'Showing matches for',
    explore: 'Browse site sections. Type above to filter.',
    empty:
      'No results. Try other words (for example: tasks, AI, about us).',
  },
  auth: {
    loginEmail: 'Email',
    loginEmailPh: 'Email',
    loginEmailErr: 'Invalid email',
    password: 'Password',
    pwdErr: 'At least 6 characters',
    forgot: 'Forgot your password?',
    signingIn: 'Signing in...',
    signIn: 'Sign in',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    registerName: 'Name',
    registerNameErr: 'At least 2 characters',
    confirmPassword: 'Confirm password',
    confirmMismatch: 'Passwords do not match',
    creating: 'Creating account...',
    createAccount: 'Create account',
    hasAccount: 'Already have an account?',
    signInHere: 'Sign in here',
  },
  userAsistente: {
    conversations: 'Conversations',
    placeholder: 'Write a message…',
    send: 'Send',
    hint: 'The assistant uses your tasks to suggest the next step.',
  },
  asistentePublic: {
    heroTitle: 'What does the AI assistant do?',
    heroSubtitle:
      'It analyzes your tasks and recommends how to organize your time intelligently.',
  },
  nosotros: {
    teamTitle: 'Development team',
    avatarAlt: 'Illustrated avatar of',
    aboutTitle: 'About the project',
    aboutLead:
      'TaskMaster is an <strong>academic prototype</strong> of a smart personal task manager: it combines a simple web interface with productivity ideas and an AI-based assistant to help you decide what to do first. It is meant to demonstrate good development practices, accessibility, and teamwork.',
    ideasLabel: 'Key ideas',
  },
  funcionalidadesPage: FUNCIONALIDADES_EN,
  productividadPage: PRODUCTIVIDAD_PAGE_EN,
  asistenteIaPage: ASISTENTE_IA_PAGE_EN,
  nosotrosPage: NOSOTROS_PAGE_EN,
  landing: LANDING_EN,
};

export type UiStrings = DeepStrings<typeof UI_ES>;
